const form=document.querySelector("#diagnosis-form"),button=document.querySelector("#start-button"),resultPanel=document.querySelector("#result-panel"),errorBanner=document.querySelector("#error-banner");let activeIncidentId=null;
const escapeHtml=(v)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const modelDefaults={fake:"",openrouter:"openrouter/free",deepseek:"deepseek-v4-flash"};
document.querySelector("#model-mode").addEventListener("change",(event)=>{const mode=event.target.value;const modelInput=document.querySelector("#model-name");if(!modelInput.value||Object.values(modelDefaults).includes(modelInput.value)){modelInput.value=modelDefaults[mode]||""}document.querySelector("#provider-hint").textContent=`${mode==='deepseek'?'DeepSeek':mode==='openrouter'?'OpenRouter':'Fake'} provider · read-only tools`;document.querySelector(".provider-label").textContent=`${mode==='deepseek'?'DEEPSEEK':mode==='openrouter'?'OPENROUTER':'FAKE'} PROVIDER`});
async function loadRuntimeConfig(){if(location.protocol==="file:"){document.querySelector("#model-mode").value="fake";document.querySelector("#provider-hint").textContent="Local preview · open the service URL to run";document.querySelector(".provider-label").textContent="LOCAL PREVIEW";return}const configuredMode=document.body.dataset.modelMode;try{const response=await fetch("/api/runtime/config",{cache:"no-store"});if(!response.ok)throw new Error("config unavailable");const config=await response.json();const mode=config.model_mode==='real'?(config.model_provider||'openai'):'fake';document.querySelector("#model-mode").value=mode==='deepseek'?'deepseek':mode==='openrouter'?'openrouter':'fake';if(config.model_name)document.querySelector("#model-name").value=config.model_name;document.querySelector("#provider-hint").textContent=`${mode==='deepseek'?'DeepSeek':mode==='openrouter'?'OpenAI-compatible':'Fake'} provider · server token`;document.querySelector(".provider-label").textContent=`${mode==='deepseek'?'DEEPSEEK':mode==='openrouter'?'OPENROUTER':mode==='openai'?'OPENAI':'FAKE'} PROVIDER`}catch(error){if(!configuredMode){document.querySelector("#provider-hint").textContent="Provider unavailable · check the service";document.querySelector(".provider-label").textContent="OFFLINE"}}}
function showError(message){errorBanner.textContent=message;errorBanner.classList.remove("hidden")}
function renderResult(result){
  resultPanel.classList.remove("hidden");
  const final=result.final,refs=[...new Map((result.evidence_refs||[]).map(r=>[r.evidence_id,r])).values()];
  document.querySelector("#diagnosis-card").innerHTML=final?`<div class="diagnosis-label">FINAL DIAGNOSIS</div><div class="diagnosis-text">${escapeHtml(final.diagnosis)}</div><div class="diagnosis-summary">${escapeHtml(final.summary)}</div><div class="confidence">Confidence <strong>${Math.round(final.confidence*100)}%</strong></div><div class="evidence-list">${refs.map(r=>`<span class="evidence-ref">◈ ${escapeHtml(r.evidence_id)}</span>`).join("")}</div>`:`<div class="diagnosis-text">${escapeHtml(result.error?.message||"Diagnosis did not complete")}</div>`;
  document.querySelector("#timeline").innerHTML=(result.turns||[]).map((turn,i)=>{const tasks=(result.tasks||[]).filter(t=>t.turn_id===turn.turn_id);return`<article class="turn"><div class="turn-heading"><strong>Turn ${i+1}</strong><span class="state">${escapeHtml(turn.status)}</span></div>${tasks.map(task=>`<div class="task"><div class="task-heading"><span class="chevron">⌄</span><strong>${escapeHtml(task.objective)}</strong><span class="state">${escapeHtml(task.status)}</span></div><div class="tool-row">${(result.tool_calls||[]).filter(c=>task.tool_call_ids.includes(c.tool_call_id)).map(c=>`<span class="tool-chip">⚙ ${escapeHtml(c.tool_name)}</span>`).join("")}</div></div>`).join("")}</article>`}).join("");
  document.querySelector("#inspector-status").textContent=result.status;document.querySelector("#session-id").textContent=result.session_id;document.querySelector("#turn-count").textContent=result.turn_count;
  document.querySelector("#execution-tree").innerHTML=(result.turns||[]).map((turn,i)=>`<div class="tree-turn"><strong>Turn ${i+1}</strong>${(result.tasks||[]).filter(t=>t.turn_id===turn.turn_id).map(task=>`<div class="tree-task">${escapeHtml(task.objective)}<div>${(result.tool_calls||[]).filter(c=>task.tool_call_ids.includes(c.tool_call_id)).map(c=>`<div class="tree-tool">${escapeHtml(c.tool_name)}</div>`).join("")}</div>`).join("")}</div>`).join("");
  document.querySelector("#inspector-evidence").innerHTML=refs.length?refs.map(r=>`<div class="evidence-mini">${escapeHtml(r.evidence_id)}</div>`).join(""):"<div class=\"empty-detail\">暂无 EvidenceRef</div>";
}
function showRunning(started){
  resultPanel.classList.remove("hidden");
  document.querySelector("#diagnosis-card").innerHTML='<div class="diagnosis-label">LIVE RUNTIME</div><div class="diagnosis-text">诊断正在运行…</div><div class="diagnosis-summary">事件会实时显示在下方时间线中</div>';
  document.querySelector("#timeline").innerHTML="";
  document.querySelector("#inspector-status").textContent="running";
  document.querySelector("#session-id").textContent=started.session_id;
  document.querySelector("#turn-count").textContent="0";
  document.querySelector("#execution-tree").innerHTML='<div class="empty-detail">等待 Runtime Event…</div>';
  document.querySelector("#inspector-evidence").innerHTML='<div class="empty-detail">等待 EvidenceRef…</div>';
}
function appendRuntimeEvent(event){
  const payload=JSON.parse(event.data||"{}");
  const timeline=document.querySelector("#timeline");
  const label={"session.started":"Session started","turn.started":"Turn started","model.started":"Model call started","model.completed":"Model response received","tool.completed":"Tool completed","task.completed":"Task completed","diagnosis.completed":"Diagnosis complete","runtime.failed":"Runtime failed"}[event.type]||event.type;
  const detail=payload.tool_name||payload.summary||payload.message||event.type;
  const item=document.createElement("div");item.className="live-event";item.innerHTML=`<span class="live-dot"></span><span>${escapeHtml(label)}</span><span class="live-detail">${escapeHtml(detail)}</span>`;timeline.appendChild(item);timeline.scrollIntoView({block:"end"});
  if(payload.turn_id)document.querySelector("#turn-count").textContent=Math.max(Number(document.querySelector("#turn-count").textContent)||0,Number(payload.turn_count)||1);
  document.querySelector("#inspector-status").textContent=event.type==="diagnosis.completed"?"completed":event.type==="runtime.failed"?"failed":"running";
}
async function watchSession(sessionId){
  return new Promise((resolve,reject)=>{const source=new EventSource(`/api/sessions/${sessionId}/events`);const terminal=new Set(["diagnosis.completed","runtime.failed"]);["session.started","turn.started","model.started","model.completed","tool.completed","task.completed","diagnosis.completed","runtime.failed"].forEach(type=>source.addEventListener(type,appendRuntimeEvent));source.addEventListener("diagnosis.completed",async()=>{source.close();try{resolve(await (await fetch(`/api/sessions/${sessionId}`)).json())}catch(error){reject(error)}});source.addEventListener("runtime.failed",async()=>{source.close();try{resolve(await (await fetch(`/api/sessions/${sessionId}`)).json())}catch(error){reject(error)}});source.onerror=()=>{if(source.readyState===EventSource.CLOSED){source.close();reject(new Error("事件流已断开，请通过 Session 查询重试"))}}});
}
form.addEventListener("submit",async(e)=>{e.preventDefault();errorBanner.classList.add("hidden");button.disabled=true;button.textContent="…";try{const data=Object.fromEntries(new FormData(form));const ir=await fetch("/api/incidents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:data.title,summary:data.summary||null,source:data.source})});if(!ir.ok)throw new Error("无法创建 Incident");const incident=await ir.json();activeIncidentId=incident.incident_id;const sr=await fetch(`/api/incidents/${incident.incident_id}/sessions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({participant_ids:[data.participant],model_mode:data.model_mode,model_name:data.model_name,api_key:data.api_key||null})});const started=await sr.json();if(!sr.ok)throw new Error(started.detail?.message||"诊断启动失败");document.querySelector("#api-token").value="";showRunning(started);const result=await watchSession(started.session_id);renderResult(result)}catch(err){showError(err.message||"网络请求失败，请稍后查询 Session")}finally{document.querySelector("#api-token").value="";button.disabled=false;button.textContent="↑"}});
document.querySelector("#new-incident").addEventListener("click",()=>{activeIncidentId=null;form.reset();document.querySelector("#title").focus();document.querySelector("#result-panel").classList.add("hidden");document.querySelector("#history-list").innerHTML='<div class="history-item selected">新 Incident</div>'});
document.querySelector("#new-session").addEventListener("click",async()=>{if(!activeIncidentId){showError("请先创建或选择一个 Incident");return}const data=Object.fromEntries(new FormData(form));try{const response=await fetch(`/api/incidents/${activeIncidentId}/sessions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({participant_ids:[data.participant],model_mode:data.model_mode,model_name:data.model_name,api_key:data.api_key||null})});const started=await response.json();if(!response.ok)throw new Error(started.detail?.message||"新对话创建失败");showRunning(started);renderResult(await watchSession(started.session_id))}catch(error){showError(error.message||"新对话创建失败")}});
async function loadIncidentHistory(){try{const items=await (await fetch('/api/observability/tree',{cache:'no-store'})).json();document.querySelector('#history-list').innerHTML=items.map(i=>`<div class="history-item ${i.incident_id===activeIncidentId?'selected':''}" data-incident="${escapeHtml(i.incident_id)}"><strong>${escapeHtml(i.title)}</strong>${i.sessions.map((s,index)=>`<div class="history-session">↳ 对话 ${index+1} · ${escapeHtml(s.status)}</div>`).join('')}</div>`).join('')||'<div class="history-item empty-history">暂无 Incident</div>';document.querySelectorAll('[data-incident]').forEach(item=>item.onclick=()=>{activeIncidentId=item.dataset.incident})}catch(error){}}
const renderResultWithHistory=renderResult;renderResult=(result)=>{renderResultWithHistory(result);loadIncidentHistory()};loadRuntimeConfig();loadIncidentHistory();
document.addEventListener("submit",async event=>{if(!activeIncidentId)return;event.preventDefault();event.stopImmediatePropagation();errorBanner.classList.add("hidden");button.disabled=true;button.textContent="…";try{const data=Object.fromEntries(new FormData(form));const response=await fetch(`/api/incidents/${activeIncidentId}/sessions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({participant_ids:[data.participant],model_mode:data.model_mode,model_name:data.model_name,api_key:data.api_key||null})});const started=await response.json();if(!response.ok)throw new Error(started.detail?.message||"新对话创建失败");document.querySelector("#api-token").value="";showRunning(started);renderResult(await watchSession(started.session_id))}catch(error){showError(error.message||"新对话创建失败")}finally{document.querySelector("#api-token").value="";button.disabled=false;button.textContent="↑"}},true);
const renderResultWithSession=renderResult;renderResult=(result)=>{activeSessionId=result.session_id;renderResultWithSession(result);renderConversationMessages(result.messages||[])};
document.querySelector("#send-message").addEventListener("click",async()=>{if(!activeSessionId){showError("请先创建一个对话");return}const content=document.querySelector("#summary").value.trim()||document.querySelector("#title").value.trim();if(!content){showError("请输入对话内容");return}const response=await fetch(`/api/sessions/${activeSessionId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})});const result=await response.json();if(!response.ok){showError(result.detail?.message||"消息发送失败");return}document.querySelector("#summary").value="";renderResult(await (await fetch(`/api/sessions/${activeSessionId}`)).json())});
function showProjectCreated(project){resultPanel.classList.remove("hidden");document.querySelector("#diagnosis-card").innerHTML=`<div class="diagnosis-label">PROJECT CREATED</div><div class="diagnosis-text">项目已创建</div><div class="diagnosis-summary">${escapeHtml(project.title)}<br>点击“新对话”开始日常对话。</div>`;document.querySelector("#timeline").innerHTML="";document.querySelector("#inspector-status").textContent="ready";document.querySelector("#session-id").textContent="—";document.querySelector("#turn-count").textContent="0";document.querySelector("#execution-tree").innerHTML='<div class="empty-detail">创建新对话后显示执行链路</div>';document.querySelector("#inspector-evidence").innerHTML='<div class="empty-detail">暂无 EvidenceRef</div>'}
document.addEventListener("submit",async event=>{event.preventDefault();event.stopImmediatePropagation();errorBanner.classList.add("hidden");const data=Object.fromEntries(new FormData(form));if(activeIncidentId){const response=await fetch(`/api/incidents/${activeIncidentId}/sessions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({participant_ids:[data.participant],model_mode:data.model_mode,model_name:data.model_name,api_key:data.api_key||null})});const started=await response.json();if(!response.ok){showError(started.detail?.message||"新对话创建失败");return}showRunning(started);renderResult(await watchSession(started.session_id));return}button.disabled=true;try{const response=await fetch("/api/incidents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:data.title,summary:data.summary||data.title,source:data.source})});const project=await response.json();if(!response.ok)throw new Error(project.detail?.message||"项目创建失败");activeIncidentId=project.incident_id;showProjectCreated(project);loadIncidentHistory()}catch(error){showError(error.message||"项目创建失败")}finally{button.disabled=false}},true);
function renderConversationMessages(messages){const target=document.querySelector("#conversation-messages");if(!target)return;target.innerHTML=(messages||[]).map(message=>`<div class="conversation-message ${message.role}"><span>${message.role==='user'?'你':'AntiSentinel'}</span><p>${escapeHtml(message.content)}</p></div>`).join('')}
